'use strict';

function createFamilyChat({onRequest,admin,db,OPENAI_API_KEY,ALLOWED_ORIGINS}){
  const OpenAI=require('openai');
  function cors(req,res){const origin=req.headers.origin;if(origin&&ALLOWED_ORIGINS.has(origin))res.set('Access-Control-Allow-Origin',origin);res.set('Vary','Origin');res.set('Access-Control-Allow-Headers','Authorization, Content-Type');res.set('Access-Control-Allow-Methods','POST, OPTIONS');}
  async function auth(req){const v=String(req.headers.authorization||'');if(!v.startsWith('Bearer '))throw Object.assign(new Error('Missing sign-in token'),{status:401});try{return await admin.auth().verifyIdToken(v.slice(7));}catch{throw Object.assign(new Error('Invalid sign-in token'),{status:401});}}
  const cutoff=days=>{const d=new Date();d.setDate(d.getDate()-days);return d.toISOString().slice(0,10);};
  const byWhen=(a,b)=>`${a.date||''}${a.time||''}`.localeCompare(`${b.date||''}${b.time||''}`);
  const cleanMom=e=>({id:e.id||null,type:e.type||null,date:e.date||null,time:e.time||null,amountMl:e.amountMl??null,durationMinutes:e.durationMinutes??e.duration??null,side:e.side||null,voidedAt:e.voidedAt||null});
  const cleanBaby=e=>({id:e.id||null,babyId:e.babyId||e.baby_id||null,eventType:e.eventType||e.event_type||null,date:e.date||null,time:e.time||null,subtype:e.subtype||null,feedingType:e.feedingType||e.feeding_type||null,amountOz:e.amountOz??e.amount_oz??null,durationMinutes:e.durationMinutes??e.duration_minutes??null,totalMinutes:e.totalMinutes??e.total_minutes??null,leftMinutes:e.leftMinutes??e.left_minutes??null,rightMinutes:e.rightMinutes??e.right_minutes??null,side:e.side||null,weightLb:e.weightLb??e.weight_lb??null,weightOz:e.weightOz??e.weight_oz??null,lengthIn:e.lengthIn??e.length_in??null,headIn:e.headIn??e.head_in??null,milestoneText:e.milestoneText??e.milestone_text??null,voidedAt:e.voidedAt||null});
  function pumpDays(entries,overrides={}){const map={};for(const e of entries){if(e.type!=='pump'||e.voidedAt||!e.date)continue;const d=map[e.date]||(map[e.date]={date:e.date,count:0,totalMl:0,sessions:[]});d.count++;d.totalMl+=Number(e.amountMl)||0;d.sessions.push({time:e.time||null,amountMl:Number(e.amountMl)||0});}for(const d of Object.values(map)){d.sessions.sort((a,b)=>String(a.time).localeCompare(String(b.time)));const o=Number(overrides?.[d.date]);if(Number.isFinite(o)&&o>d.totalMl)d.totalMl=o;}return Object.values(map).sort((a,b)=>a.date.localeCompare(b.date)).slice(-14);}
  function babyDays(events){const map={};for(const e of events){if(e.voidedAt||!e.date)continue;const key=`${e.babyId||'baby'}:${e.date}`,d=map[key]||(map[key]={babyId:e.babyId||null,date:e.date,nursing:0,nursingMinutes:0,feeds:0,feedOz:0,wet:0,poop:0,both:0});const t=e.eventType;if(t==='nursing'){d.nursing++;d.nursingMinutes+=Number(e.totalMinutes??e.durationMinutes)||0;}else if(t==='feeding'){d.feeds++;d.feedOz+=Number(e.amountOz)||0;}else if(t==='diaper'){const s=String(e.subtype||'').toLowerCase();if(s==='wet')d.wet++;else if(s==='poop'||s==='dirty')d.poop++;else if(s==='both'||s==='mixed')d.both++;}}return Object.values(map).sort((a,b)=>`${a.date}${a.babyId||''}`.localeCompare(`${b.date}${b.babyId||''}`)).slice(-21);}
  function childSummaries(events){const map={};for(const e of events){const id=e.babyId||'unassigned',x=map[id]||(map[id]={babyId:id,eventCount:0,lastEventDate:null,types:{}});x.eventCount++;x.lastEventDate=!x.lastEventDate||String(e.date||'')>x.lastEventDate?e.date:x.lastEventDate;const t=e.eventType||'other';x.types[t]=(x.types[t]||0)+1;}return Object.values(map);}
  async function load(uid){const root=db.collection('users').doc(uid);const [momSnap,babySnap,profileDoc,chatSnap]=await Promise.all([root.collection('entries').where('date','>=',cutoff(45)).get(),root.collection('familyEvents').where('date','>=',cutoff(90)).get(),root.collection('private').doc('profile').get(),root.collection('familyChatMessages').orderBy('createdAt','desc').limit(30).get().catch(()=>null)]);const raw=profileDoc.exists?(profileDoc.data()||{}):{},mom=momSnap.docs.map(d=>cleanMom({id:d.id,...d.data()})).filter(e=>!e.voidedAt).sort(byWhen),baby=babySnap.docs.map(d=>cleanBaby({id:d.id,...d.data()})).filter(e=>!e.voidedAt).sort(byWhen),history=chatSnap?chatSnap.docs.map(d=>d.data()).reverse().map(x=>({role:x.role==='assistant'?'assistant':'user',text:String(x.text||'').slice(0,2200)})):[];return{profile:{dailyGoalMl:raw.profile?.dailyGoalMl??raw.dailyGoalMl??null,schedule:Array.isArray(raw.schedule)?raw.schedule:[],baby:raw.baby||null},pumpDays:pumpDays(mom,raw.dailyOverrides||{}),recentMom:mom.slice(-40),children:childSummaries(baby),babyDays:babyDays(baby),recentBaby:baby.slice(-90),history};}

  const SYSTEM=`You are MilkFlow Pumping Chat, the user's private pumping assistant inside their tracker. Stay focused on pumping logs, totals, spacing, schedules, supply patterns, and today's or tomorrow's pump-count choice. Talk like a warm, attentive human assistant, not a clinical dashboard. Continue the conversation naturally: acknowledge what the user just told you, connect it with recent conversation and tracker history, and then give the useful next step. Light, natural emoji use is welcome when it fits.

Use only supplied tracker/context data for facts and never invent a record. Actual logged pump times and dynamicPlan are the source of truth for today's next-pump timing. Use multi-day patterns when discussing trends. If the day started late, the user slept poorly, or a session moved, do not scold them or tell them to cram catch-up pumps together; explain the adaptive plan from what is actually logged. A 5- or 6-pump selection is date-specific: choosing 5 today must never be described as changing every future day. Use pumpChoices to distinguish today from tomorrow. The app can set today's or tomorrow's count and move today's next pump in chat.

Do not diagnose or claim a medical guarantee. If there is a red-flag health situation, recommend appropriate professional care without being alarmist.

Prefer a friendly answer first, then compact numbers/timing. For a newly logged pump, mention today's running total when available, the rolling pattern if relevant, and next timing. Keep normal replies under about 260 words unless the user asks for more detail.`;
  const schema={type:'object',additionalProperties:false,properties:{reply:{type:'string'},topic:{type:'string',enum:['mom','baby','family','other']},needs_attention:{type:'boolean'}},required:['reply','topic','needs_attention']};
  async function callModel(payload){const client=new OpenAI({apiKey:OPENAI_API_KEY.value()}),models=[process.env.OPENAI_MODEL||'gpt-5.6-sol','gpt-5.6-terra'];let last;for(const model of [...new Set(models)]){try{const r=await client.responses.create({model,reasoning:{effort:'medium'},max_output_tokens:1200,input:[{role:'system',content:[{type:'input_text',text:SYSTEM}]},{role:'user',content:[{type:'input_text',text:JSON.stringify(payload)}]}],text:{format:{type:'json_schema',name:'milkflow_family_chat',strict:true,schema}}});const parsed=JSON.parse(String(r.output_text||'{}'));if(!parsed.reply)throw new Error('Empty reply');return{reply:String(parsed.reply).slice(0,6000),topic:parsed.topic||'family',needs_attention:!!parsed.needs_attention,model,responseId:r.id||null,source:'ai'};}catch(err){last=err;console.warn(`Family chat attempt failed on ${model}`,err?.message||err);}}throw last||new Error('Family chat unavailable');}
  function rulesReply(p){
    const q=String(p.userMessage||'').toLowerCase(),plan=p.dynamicPlan||{},days=Array.isArray(p.pumpDays)?p.pumpDays:[],babyDaysList=Array.isArray(p.babyDays)?p.babyDays:[];
    if(/sleep|slept|alarm|woke|wake|tired|exhausted|overslept/.test(q)){let timing='';if(plan.remaining&&Array.isArray(plan.future)&&plan.future.length){const m=Number(plan.future[0]),h=Math.floor(((m%1440)+1440)%1440/60),mm=((m%60)+60)%60,t=`${((h+11)%12)+1}:${String(mm).padStart(2,'0')} ${h>=12?'PM':'AM'}`;timing=` Your current live plan has the next pump around ${t}.`;}return{reply:`That sounds like a rough night 💛 You do not need to chase the old clock today. MilkFlow can move the remaining plan from what you actually log.${timing}`,topic:'mom',needs_attention:false,model:null,responseId:null,source:'rules'};}
    if(/next.*pump|when.*pump|pump.*next/.test(q)&&plan.remaining&&Array.isArray(plan.future)&&plan.future.length){const m=Number(plan.future[0]),h=Math.floor(((m%1440)+1440)%1440/60),mm=((m%60)+60)%60,t=`${((h+11)%12)+1}:${String(mm).padStart(2,'0')} ${h>=12?'PM':'AM'}`;return{reply:`Your live plan puts the next pump around ${t} 💛 That is based on what you actually logged today, not the old fixed clock. You can also change today's pump count or move the next pump directly in chat.`,topic:'mom',needs_attention:false,model:null,responseId:null,source:'rules'};}
    if(/7.?day|rolling|pump.*table|pumping.*summary/.test(q)&&days.length){return{reply:`🌷 Recent pumping\n${days.slice(-7).map(d=>`${d.date}: ${d.totalMl} mL · ${d.count} pump${d.count===1?'':'s'}`).join('\n')}`,topic:'mom',needs_attention:false,model:null,responseId:null,source:'rules'};}
    if(/baby|breast|nurs|diaper|wet|poop|poopy|mixed|feed/.test(q)){const d=babyDaysList.at(-1);if(d)return{reply:`${d.date} for Baby 💛 ${d.nursing} breastfeeding session${d.nursing===1?'':'s'}${d.nursingMinutes?` (${d.nursingMinutes} min logged)`:''}, ${d.feeds} bottle feed${d.feeds===1?'':'s'}, ${d.wet} wet, ${d.poop} poopy, and ${d.both} mixed diapers.`,topic:'baby',needs_attention:false,model:null,responseId:null,source:'rules'};}
    return{reply:'I’m here 💛 I can use your MilkFlow history and today’s live plan. Tell me what happened, ask what to do next, or log a pump/feed/diaper naturally.',topic:'family',needs_attention:false,model:null,responseId:null,source:'rules'};
  }

  return onRequest({region:'us-central1',secrets:[OPENAI_API_KEY],timeoutSeconds:30,memory:'256MiB'},async(req,res)=>{
    cors(req,res);if(req.method==='OPTIONS')return res.status(204).send('');if(req.method!=='POST')return res.status(405).json({ok:false,error:'POST required'});
    try{
      const decoded=await auth(req),uid=decoded.uid,message=String(req.body?.message||'').trim().slice(0,3000);if(!message)return res.status(400).json({ok:false,error:'Message required'});
      const local=req.body?.context&&typeof req.body.context==='object'?req.body.context:{};
      let cloud={profile:{},pumpDays:[],recentMom:[],children:[],babyDays:[],recentBaby:[],history:[]};
      try{cloud=await load(uid);}catch(err){console.warn('Family chat cloud context unavailable; using device context',err?.message||err);}
      const localConversation=Array.isArray(local.localConversation)?local.localConversation.slice(-16).map(x=>({role:x.role==='assistant'?'assistant':'user',text:String(x.text||'').slice(0,1200)})):[];
      const payload={currentLocalTime:local.currentLocalTime||null,timeZone:local.timeZone||null,currentWorkspace:local.currentWorkspace||null,dynamicPlan:local.dynamicPlan||null,pumpChoices:local.pumpChoices||null,activeBaby:local.activeBaby||null,localRecentMom:Array.isArray(local.recentMom)?local.recentMom.slice(-24):[],profile:cloud.profile,pumpDays:cloud.pumpDays,recentMom:cloud.recentMom,conversation:cloud.history.slice(-24),deviceConversation:localConversation,userMessage:message};
      let out;try{out=await callModel(payload);}catch(err){console.warn('Using family chat tracker fallback',err?.message||err);out=rulesReply(payload);}
      const col=db.collection('users').doc(uid).collection('familyChatMessages'),batch=db.batch();batch.set(col.doc(),{role:'user',text:message,createdAt:admin.firestore.FieldValue.serverTimestamp()});batch.set(col.doc(),{role:'assistant',text:out.reply,topic:out.topic,needsAttention:out.needs_attention,model:out.model||null,source:out.source||'rules',responseId:out.responseId||null,createdAt:admin.firestore.FieldValue.serverTimestamp()});await batch.commit().catch(err=>console.warn('Family chat history save skipped',err?.message||err));
      return res.status(200).json({ok:true,...out,generatedAt:new Date().toISOString()});
    }catch(err){const status=err?.status||500;console.error('familyChat request rejected',err?.message||err);return res.status(status).json({ok:false,error:status===401?'Please sign in again.':'MilkFlow chat could not be processed.'});}
  });
}
module.exports={createFamilyChat};
