(() => {
'use strict';
const KEY='milkflow-family-v4-state';
const LEGACY=['milkflow-v3-state','milkflow-v2-state'];
const defaults={
 version:5,
 profile:{dailyGoalMl:760,babyMinOz:20,babyMaxOz:22,stashMl:0},
 baby:{id:'saahas-2026',name:'Saahas'},
 schedule:['05:40','11:05','14:35','17:45','20:45','23:35'],
 entries:[],babyEvents:[],dailyOverrides:{},
 reminders:{enabled:false,leadMin:10,lastSentKey:null},
 cloud:{enabled:false,userId:null,email:null,lastSync:null},
 ui:{view:'mom-home'}
};
const $=id=>document.getElementById(id);
const clone=o=>JSON.parse(JSON.stringify(o));
const sum=a=>a.reduce((x,y)=>x+y,0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const isoDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const today=()=>isoDate(new Date());
const now=()=>{const d=new Date();return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`};
const fd=d=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(new Date(`${d}T12:00:00`));
const fdl=d=>new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric'}).format(new Date(`${d}T12:00:00`));
const to12=t=>{if(!t)return'—';const[h,m]=t.split(':').map(Number);return`${((h+11)%12)+1}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`};
const cap=s=>String(s||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
function load(){
 for(const k of [KEY,...LEGACY]){
  try{
   const raw=localStorage.getItem(k); if(!raw) continue;
   const p=JSON.parse(raw);
   return {...clone(defaults),...p,profile:{...defaults.profile,...(p.profile||{})},baby:{...defaults.baby,...(p.baby||{})},reminders:{...defaults.reminders,...(p.reminders||{})},cloud:{...defaults.cloud,...(p.cloud||{})},ui:{...defaults.ui,...(p.ui||{})},entries:p.entries||[],babyEvents:p.babyEvents||[],dailyOverrides:p.dailyOverrides||{}};
  }catch{}
 }
 return clone(defaults);
}
const S=load();
let cloud=null;
let view=(location.hash||'').replace('#','')||S.ui.view||'mom-home';
const validViews=new Set(['mom-home','today','history','trends','stash','baby-home','baby-history','doctor','settings']);
if(!validViews.has(view)) view='mom-home';
function save(){S.ui.view=view;localStorage.setItem(KEY,JSON.stringify(S));}
function setView(v){if(!validViews.has(v))v='mom-home';view=v;S.ui.view=v;save();if(location.hash!==`#${v}`) history.replaceState(null,'',`#${v}`);render();window.scrollTo({top:0,behavior:'smooth'});}
window.addEventListener('hashchange',()=>{const v=location.hash.replace('#','');if(validViews.has(v)&&v!==view){view=v;S.ui.view=v;save();render();}});
function toast(msg){const t=$('toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2600);}
function icon(name,cls=''){const p={home:'<path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5"/><path d="M9 20v-6h6v6"/>',drop:'<path d="M12 3s6 6.2 6 11a6 6 0 0 1-12 0c0-4.8 6-11 6-11Z"/>',history:'<path d="M3 12a9 9 0 1 0 3-6.7"/><path d="M3 4v5h5"/><path d="M12 8v4l3 2"/>',chart:'<path d="M4 19V5"/><path d="M4 19h16"/><path d="m7 15 3-4 3 2 4-6"/>',snow:'<path d="M12 2v20M4.2 6.5l15.6 9M4.2 17.5l15.6-9"/>',baby:'<circle cx="12" cy="12" r="8"/><path d="M9.5 10h.01M14.5 10h.01M9.5 14c1.6 1.2 3.4 1.2 5 0"/><path d="M8 4.7c1.2-1.9 3.7-2.3 5.3-.8"/>',diaper:'<path d="M5 7c2.3 1.4 4.6 2.1 7 2.1S16.7 8.4 19 7v8.5c-2.1 2.3-4.5 3.5-7 3.5s-4.9-1.2-7-3.5Z"/><path d="M8 9.1v7.1M16 9.1v7.1"/>',bottle:'<path d="M9 3h6M10 3v4l-2 3v9a2 2 0 0 0 2 2h4a2 2 0 0 0 2-2v-9l-2-3V3"/><path d="M8 13h8"/>',steth:'<path d="M6 3v5a4 4 0 0 0 8 0V3"/><path d="M10 12v2a5 5 0 0 0 10 0v-1"/><circle cx="20" cy="10" r="2"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.4 1a7 7 0 0 0-1.7-1L14.5 3h-5l-.3 3.1a7 7 0 0 0-1.7 1l-2.4-1-2 3.4L5.1 11a7 7 0 0 0 0 2l-2 1.5 2 3.4 2.4-1a7 7 0 0 0 1.7 1l.3 3.1h5l.3-3.1a7 7 0 0 0 1.7-1l2.4 1 2-3.4-2-1.5c.1-.3.1-.7.1-1Z"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.6l-1-1a5.5 5.5 0 0 0-7.8 7.8L12 21l7.8-7.6a5.5 5.5 0 0 0 0-7.8Z"/>',plus:'<path d="M12 5v14M5 12h14"/>',check:'<path d="m5 12 4 4L19 6"/>'};return `<svg class="ico ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${p[name]||p.heart}</svg>`;}
const pumps=()=>S.entries.filter(e=>e.type==='pump');const nurses=()=>S.entries.filter(e=>e.type==='nursing');const dayP=d=>pumps().filter(e=>e.date===d).sort((a,b)=>(a.time||'').localeCompare(b.time||''));const calc=d=>sum(dayP(d).map(e=>+e.amountMl||0));const dayTotal=d=>Number.isFinite(+S.dailyOverrides?.[d])?+S.dailyOverrides[d]:calc(d);const babyFor=(d,type)=>S.babyEvents.filter(e=>e.date===d&&(!type||e.eventType===type));
function lastDates(n,end=today()){const out=[],d=new Date(`${end}T12:00:00`);for(let i=n-1;i>=0;i--){const x=new Date(d);x.setDate(d.getDate()-i);out.push(isoDate(x));}return out;}
function rollingPumpAvg(n=7){const vals=lastDates(n).map(dayTotal).filter(v=>v>0);return vals.length?Math.round(sum(vals)/vals.length):0;}function lastPump(){return pumps().slice().sort((a,b)=>(b.date+(b.time||'')).localeCompare(a.date+(a.time||'')))[0]||null;}function nextSlot(){const d=new Date(),m=d.getHours()*60+d.getMinutes();return S.schedule.map(t=>({t,m:+t.slice(0,2)*60 + +t.slice(3)})).find(x=>x.m>m)?.t||S.schedule[0];}
function card(label,value,sub,ic,tone='mom'){return `<article class="metric-card ${tone}"><div class="metric-icon">${icon(ic)}</div><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-sub">${sub}</div></article>`;}function empty(ic,title,sub,action=''){return `<div class="empty-state"><div class="empty-icon">${icon(ic)}</div><strong>${title}</strong><span>${sub}</span>${action}</div>`;}
function momHero(){const lp=lastPump();return `<section class="hero mom-hero"><div><span class="eyebrow">MOM</span><h2>${dayTotal(today())?`${dayTotal(today())} mL today`:'Ready when you are'}</h2><div class="hero-actions"><button class="action primary" data-pump>${icon('drop')}<span>Pump</span></button><button class="action soft" data-nurse>${icon('heart')}<span>Nursing</span></button></div></div><div class="hero-art">${icon('drop','hero-drop')}<span></span></div></section><div class="metric-grid">${card('Today',`${dayTotal(today())} mL`,`${dayP(today()).length} pumps`,'drop')}${card('7-day avg',`${rollingPumpAvg()} mL`,'recent pumping days','chart')}${card('Next',to12(nextSlot()),lp?`last ${to12(lp.time)}`:'no pump yet','bell')}${card('Stash',`${(+S.profile.stashMl||0).toLocaleString()} mL`,'freezer','snow')}</div>`;}
function scheduleStrip(){const d=today(),a=dayP(d),n=new Date(),nm=n.getHours()*60+n.getMinutes();return `<div class="schedule-strip">${S.schedule.map((t,i)=>{const e=a[i],sm=+t.slice(0,2)*60 + +t.slice(3),cls=e?'done':(!e&&sm>=nm&&a.length===i?'next':'');return `<div class="slot ${cls}"><div class="slot-icon">${e?icon('check'):icon('bell')}</div><strong>${e?to12(e.time):to12(t)}</strong><span>${e?`${e.amountMl} mL`:'Pump'}</span></div>`}).join('')}</div>`;}
function recentMom(n=5){const a=S.entries.slice().sort((x,y)=>(y.date+(y.time||'')).localeCompare(x.date+(x.time||''))).slice(0,n);if(!a.length)return empty('history','No pumping history yet','Import the complete family backup or add your first pump.','<button class="action soft" data-view="settings">Open settings</button>');return `<div class="list">${a.map(e=>`<button class="list-row" data-view="history"><span class="row-icon">${icon(e.type==='pump'?'drop':'heart')}</span><span><strong>${e.type==='pump'?`${e.amountMl||0} mL`:`${e.durationMin||0} min nursing`}</strong><small>${fd(e.date)} · ${to12(e.time)}</small></span><b>›</b></button>`).join('')}</div>`;}
function momHome(){return `${momHero()}<section class="panel"><div class="panel-head"><h3>Today</h3><button data-view="today">Open</button></div>${scheduleStrip()}</section><div class="two-col"><section class="panel"><div class="panel-head"><h3>Recent</h3><button data-view="history">All</button></div>${recentMom()}</section><section class="panel"><div class="panel-head"><h3>Quick view</h3><button data-view="trends">Trends</button></div><div class="visual-stat"><div class="ring" style="--p:${Math.min(100,Math.round(dayTotal(today())/(+S.profile.dailyGoalMl||760)*100))}%"><span>${Math.min(100,Math.round(dayTotal(today())/(+S.profile.dailyGoalMl||760)*100))}%</span></div><div><strong>${+S.profile.dailyGoalMl||760} mL goal</strong><small>Adjust in Settings</small></div></div></section></div>`;}
function todayView(){const p=dayP(today()),n=nurses().filter(e=>e.date===today());if(!p.length&&!n.length)return `<section class="hero compact"><div><span class="eyebrow">${fdl(today())}</span><h2>No entries today</h2><div class="hero-actions"><button class="action primary" data-pump>${icon('drop')}<span>Pump</span></button><button class="action soft" data-view="history">${icon('history')}<span>History</span></button></div></div></section><section class="panel">${empty('history','Your history is still available','Today starts empty until something is logged.')}</section>`;return `<section class="hero compact"><div><span class="eyebrow">${fdl(today())}</span><h2>${dayTotal(today())} mL</h2><small>${p.length} pumps · ${n.length} nursing</small></div></section><section class="panel"><div class="panel-head"><h3>Pumps</h3><button data-pump>Add</button></div>${momRows(p)}</section>${n.length?`<section class="panel"><div class="panel-head"><h3>Nursing</h3></div>${momRows(n)}</section>`:''}`;}
function momRows(a){if(!a.length)return empty('drop','No entries','');return `<div class="history-list">${a.slice().sort((x,y)=>(y.date+(y.time||'')).localeCompare(x.date+(x.time||''))).map(e=>`<div class="history-row"><span class="row-icon">${icon(e.type==='pump'?'drop':'heart')}</span><div><strong>${e.type==='pump'?`${e.amountMl||0} mL`:`${e.durationMin||0} min`}</strong><small>${fd(e.date)} · ${to12(e.time)}${e.side?` · ${cap(e.side)}`:''}</small></div><button class="mini danger" data-del-mom="${e.id}">Delete</button></div>`).join('')}</div>`;}
function historyView(){const a=S.entries.slice().sort((x,y)=>(y.date+(y.time||'')).localeCompare(x.date+(x.time||'')));return `<div class="view-head"><div><span class="eyebrow">MOM</span><h2>History</h2></div><button class="action primary" data-pump>${icon('plus')}<span>Pump</span></button></div><section class="panel">${a.length?momRows(a):empty('history','No Mom history found','Your Baby Tracker import does not contain the full Mom pumping history. Use the complete family import in Settings.')}</section>`;}
function trendsView(){const ds=lastDates(14),vals=ds.map(dayTotal),mx=Math.max(...vals,+S.profile.dailyGoalMl||760,1);const bars=ds.map((d,i)=>`<div class="bar-col"><span>${vals[i]||''}</span><i style="height:${Math.max(3,Math.round((vals[i]/mx)*150))}px"></i><small>${fd(d)}</small></div>`).join('');const high=pumps().reduce((m,e)=>(+e.amountMl||0)>(+m?.amountMl||0)?e:m,null);return `<div class="view-head"><div><span class="eyebrow">MOM</span><h2>Milk trends</h2></div></div><div class="metric-grid three">${card('7-day avg',`${rollingPumpAvg()} mL`,'rolling','chart')}${card('Best pump',`${high?.amountMl||0} mL`,high?fd(high.date):'—','drop')}${card('Pumps',pumps().length,'all time','history')}</div><section class="panel"><div class="panel-head"><h3>Last 14 days</h3></div><div class="bars">${bars}</div></section>`;}
function stashView(){return `<section class="hero stash-hero"><div><span class="eyebrow">MOM</span><h2>${(+S.profile.stashMl||0).toLocaleString()} mL</h2><small>Freezer stash</small></div>${icon('snow','hero-drop')}</section><section class="panel"><div class="stash-actions"><button data-stash="-60">−60</button><button data-stash="60">+60</button><button data-stash="120">+120</button></div></section>`;}
function babyStats(d=today()){const ds=babyFor(d,'diaper'),feeds=babyFor(d,'feeding');const wet=ds.filter(e=>['wet','both'].includes(e.subtype)).length;const poop=ds.filter(e=>['poop','both'].includes(e.subtype)).length;const oz=sum(feeds.map(e=>+e.amountOz||0));return {wet,poop,diapers:ds.length,feeds:feeds.length,oz};}
function babyHome(){const s=babyStats(today());return `<section class="hero baby-hero"><div><span class="eyebrow">${esc(S.baby.name)}</span><h2>Baby care</h2><div class="baby-actions"><button data-baby="wet">${icon('diaper')}<span>Wet</span></button><button data-baby="poop">${icon('diaper')}<span>Poop</span></button><button data-baby="both">${icon('diaper')}<span>Both</span></button><button data-baby="bottle">${icon('bottle')}<span>Bottle</span></button></div></div><div class="hero-art baby-art">${icon('baby','hero-baby')}</div></section><div class="metric-grid">${card('Wet',s.wet,'today','diaper','baby')}${card('Poop',s.poop,'today','diaper','baby')}${card('Feeds',s.feeds,`${s.oz.toFixed(1)} oz`,'bottle','baby')}${card('History',S.babyEvents.length.toLocaleString(),'records','history','baby')}</div><div class="two-col"><section class="panel"><div class="panel-head"><h3>Recent</h3><button data-view="baby-history">All</button></div>${recentBaby()}</section><section class="panel doctor-card"><div class="doctor-icon">${icon('steth')}</div><div><h3>Doctor summary</h3><p>Diapers, feeds and daily averages.</p><button class="action baby" data-view="doctor">Open</button></div></section></div>`;}
function babyLabel(e){if(e.eventType==='diaper')return `${cap(e.subtype||'diaper')} diaper`;if(e.eventType==='feeding')return `${(+e.amountOz||0).toFixed(1)} oz ${e.feedingType==='formula'?'formula':'milk'}`;if(e.eventType==='nursing')return `${e.totalMinutes||0} min nursing`;if(e.eventType==='sleep')return `${Math.round((+e.durationMinutes||0)/6)/10} hr sleep`;return cap(e.eventType);}
function recentBaby(n=6){const a=S.babyEvents.slice().sort((x,y)=>(y.date+(y.time||'')).localeCompare(x.date+(x.time||''))).slice(0,n);if(!a.length)return empty('baby','No baby history found','Import your Baby Tracker file in Settings.');return `<div class="list">${a.map(e=>`<button class="list-row" data-view="baby-history"><span class="row-icon baby">${icon(e.eventType==='feeding'?'bottle':e.eventType==='diaper'?'diaper':'baby')}</span><span><strong>${babyLabel(e)}</strong><small>${fd(e.date)} · ${to12(e.time)}</small></span><b>›</b></button>`).join('')}</div>`;}
function babyHistory(){const a=S.babyEvents.slice().sort((x,y)=>(y.date+(y.time||'')).localeCompare(x.date+(x.time||'')));return `<div class="view-head"><div><span class="eyebrow">BABY</span><h2>History</h2></div><div class="filter-row"><select id="babyFilter"><option value="all">All</option><option value="diaper">Diapers</option><option value="feeding">Feeds</option><option value="nursing">Nursing</option><option value="sleep">Sleep</option></select></div></div><section class="panel"><div id="babyHistoryList">${babyRows(a)}</div></section>`;}
function babyRows(a){if(!a.length)return empty('baby','No matching records','');return `<div class="history-list">${a.map(e=>`<div class="history-row"><span class="row-icon baby">${icon(e.eventType==='feeding'?'bottle':e.eventType==='diaper'?'diaper':'baby')}</span><div><strong>${babyLabel(e)}</strong><small>${fd(e.date)} · ${to12(e.time)}</small></div></div>`).join('')}</div>`;}
function doctorView(){const days=lastDates(14),rows=days.map(d=>({d,...babyStats(d)}));const active=rows.filter(r=>r.wet||r.poop||r.feeds);const avgWet=active.length?(sum(active.map(r=>r.wet))/active.length).toFixed(1):'0';const avgPoop=active.length?(sum(active.map(r=>r.poop))/active.length).toFixed(1):'0';const avgFeeds=active.length?(sum(active.map(r=>r.feeds))/active.length).toFixed(1):'0';const avgOz=active.length?(sum(active.map(r=>r.oz))/active.length).toFixed(1):'0.0';return `<div class="view-head"><div><span class="eyebrow">BABY</span><h2>Doctor summary</h2></div><button class="action soft" id="printDoctor">${icon('steth')}<span>Print</span></button></div><div class="metric-grid">${card('Wet / day',avgWet,'14-day average','diaper','baby')}${card('Poop / day',avgPoop,'14-day average','diaper','baby')}${card('Feeds / day',avgFeeds,'14-day average','bottle','baby')}${card('Milk / day',`${avgOz} oz`,'logged bottles','bottle','baby')}</div><section class="panel"><div class="panel-head"><h3>Last 14 days</h3></div><div class="doctor-table"><div class="doctor-tr head"><span>Date</span><span>Wet</span><span>Poop</span><span>Feeds</span><span>Oz</span></div>${rows.slice().reverse().map(r=>`<div class="doctor-tr"><span>${fd(r.d)}</span><span>${r.wet}</span><span>${r.poop}</span><span>${r.feeds}</span><span>${r.oz.toFixed(1)}</span></div>`).join('')}</div></section><section class="panel"><div class="panel-head"><h3>Quick answers</h3></div><div class="qa"><div><strong>Wet diapers?</strong><span>${avgWet}/day average</span></div><div><strong>Poopy diapers?</strong><span>${avgPoop}/day average</span></div><div><strong>Feeds?</strong><span>${avgFeeds}/day average</span></div><div><strong>Bottle intake?</strong><span>${avgOz} oz/day average logged</span></div></div><small class="footnote">Summary reflects logged data only and is not a diagnosis.</small></section>`;}
function settingsView(){const notif=('Notification'in window)?Notification.permission:'unsupported';const momCloud=S.entries.filter(e=>e.synced).length,babyCloud=S.babyEvents.filter(e=>e.synced).length;return `<div class="view-head"><div><span class="eyebrow">FAMILY</span><h2>Settings</h2></div></div><section class="panel settings-card"><div class="settings-icon">${icon('check')}</div><div><h3>Data</h3><p>${S.cloud.enabled?'Signed in':'This device only'}</p><div class="data-counts"><span><b>${S.entries.length}</b> Mom</span><span><b>${S.babyEvents.length}</b> Baby</span></div></div><div class="settings-actions">${S.cloud.enabled?`<button class="mini" id="checkCloud">Check cloud</button><button class="mini" id="signOutBtn">Sign out</button>`:`<button class="action primary" id="openAuthBtn">Sign in</button>`}</div></section><section class="panel settings-card"><div class="settings-icon">${icon('bell')}</div><div><h3>Pump reminders</h3><p>${notif==='granted'?'Allowed on this device':notif==='denied'?'Blocked in browser settings':'Off'}</p></div><div class="settings-actions"><button class="mini" id="toggleReminders">${S.reminders.enabled?'Turn off':'Enable'}</button></div></section><section class="panel settings-card"><div class="settings-icon">${icon('history')}</div><div><h3>Import family backup</h3><p>Safe merge. Existing records stay.</p></div><div class="settings-actions"><button class="mini" id="importBtn">Import</button></div></section><section class="panel settings-stack"><label>Daily pump goal <input id="goalMl" type="number" inputmode="numeric" value="${+S.profile.dailyGoalMl||760}"></label><label>Freezer stash <input id="stashMl" type="number" inputmode="numeric" value="${+S.profile.stashMl||0}"></label>${S.schedule.map((t,i)=>`<label>Pump ${i+1}<input data-schedule="${i}" type="time" value="${t}"></label>`).join('')}</section><section class="panel cloud-detail"><small>On device: ${S.entries.length} Mom · ${S.babyEvents.length} Baby</small><small>Marked cloud-saved: ${momCloud} Mom · ${babyCloud} Baby</small></section>`;}
const renderers={'mom-home':momHome,today:todayView,history:historyView,trends:trendsView,stash:stashView,'baby-home':babyHome,'baby-history':babyHistory,doctor:doctorView,settings:settingsView};const titles={'mom-home':'Mom',today:'Today',history:'History',trends:'Trends',stash:'Stash','baby-home':'Baby','baby-history':'Baby history',doctor:'Doctor summary',settings:'Settings'};
function render(){$('viewTitle').textContent=titles[view]||'MilkFlow';$('content').innerHTML=(renderers[view]||momHome)();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('[data-workspace]').forEach(b=>b.classList.toggle('active',b.dataset.workspace===(view.startsWith('baby')||view==='doctor'?'baby':'mom')));bindDynamic();syncBadge();}
function syncBadge(){const badge=$('cloudBadge'),title=$('syncTitle'),sub=$('syncSubtitle');const on=!!S.cloud.enabled;if(badge){badge.textContent=on?'Saved':'Device';badge.className=`cloud-badge ${on?'on':'off'}`;}if(title)title.textContent=on?'Family data saved':'On this device';if(sub)sub.textContent=on?(S.cloud.email||'Family account'):'Sign in to sync';}
function openMom(type){$('entryType').value=type;$('dialogTitle').textContent=type==='pump'?'Pump':'Nursing';$('entryDate').value=today();$('entryTime').value=now();$('entryAmount').value='';$('entryDuration').value='';$('entryNote').value='';document.querySelectorAll('.pump-only').forEach(x=>x.classList.toggle('hidden',type!=='pump'));document.querySelectorAll('.nurse-only').forEach(x=>x.classList.toggle('hidden',type!=='nursing'));$('entryDialog').showModal();}
function openBaby(kind){$('babyDate').value=today();$('babyTime').value=now();$('babyNote').value='';$('babyAmount').value='';if(['wet','poop','both'].includes(kind)){$('babyEventType').value='diaper';$('babyDialogTitle').textContent='Diaper';$('babyAmountWrap').classList.add('hidden');$('babySubtype').innerHTML='<option value="wet">Wet</option><option value="poop">Poop</option><option value="both">Wet + poop</option>';$('babySubtype').value=kind;}else{$('babyEventType').value='feeding';$('babyDialogTitle').textContent='Bottle';$('babyAmountWrap').classList.remove('hidden');$('babySubtype').innerHTML='<option value="expressed_milk">Breast milk</option><option value="formula">Formula</option>';} $('babyDialog').showModal();}
function bindDynamic(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-pump]').forEach(b=>b.onclick=()=>openMom('pump'));document.querySelectorAll('[data-nurse]').forEach(b=>b.onclick=()=>openMom('nursing'));document.querySelectorAll('[data-baby]').forEach(b=>b.onclick=()=>openBaby(b.dataset.baby));document.querySelectorAll('[data-stash]').forEach(b=>b.onclick=async()=>{S.profile.stashMl=Math.max(0,(+S.profile.stashMl||0)+ +b.dataset.stash);save();await pushProfile();render();});document.querySelectorAll('[data-del-mom]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this entry?'))return;S.entries=S.entries.filter(e=>e.id!==b.dataset.delMom);save();if(cloud&&S.cloud.userId)await momRef().doc(b.dataset.delMom).delete();render();});if($('babyFilter'))$('babyFilter').onchange=e=>{const v=e.target.value,a=S.babyEvents.filter(x=>v==='all'||x.eventType===v).slice().sort((x,y)=>(y.date+(y.time||'')).localeCompare(x.date+(x.time||'')));$('babyHistoryList').innerHTML=babyRows(a);};if($('printDoctor'))$('printDoctor').onclick=()=>window.print();if($('openAuthBtn'))$('openAuthBtn').onclick=()=>$('authDialog').showModal();if($('signOutBtn'))$('signOutBtn').onclick=()=>cloud?.auth.signOut();if($('importBtn'))$('importBtn').onclick=()=>$('importFile').click();if($('checkCloud'))$('checkCloud').onclick=checkCloud;if($('toggleReminders'))$('toggleReminders').onclick=toggleReminder;if($('goalMl'))$('goalMl').onchange=async e=>{S.profile.dailyGoalMl=+e.target.value||760;save();await pushProfile();};if($('stashMl'))$('stashMl').onchange=async e=>{S.profile.stashMl=Math.max(0,+e.target.value||0);save();await pushProfile();};document.querySelectorAll('[data-schedule]').forEach(x=>x.onchange=async()=>{S.schedule[+x.dataset.schedule]=x.value;save();await pushProfile();});}
function initStatic(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-workspace]').forEach(b=>b.onclick=()=>setView(b.dataset.workspace==='baby'?'baby-home':'mom-home'));$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');$('quickPumpBtn').onclick=()=>openMom('pump');$('quickNurseBtn').onclick=()=>openMom('nursing');$('fabBtn').onclick=()=>$('fabMenu').classList.toggle('hidden');$('fabMenu').onclick=e=>{const b=e.target.closest('[data-quick]');if(!b)return;$('fabMenu').classList.add('hidden');['pump','nursing'].includes(b.dataset.quick)?openMom(b.dataset.quick):openBaby(b.dataset.quick);};$('entryForm').addEventListener('submit',async e=>{e.preventDefault();const type=$('entryType').value;const x={id:`mom-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,type,date:$('entryDate').value,time:$('entryTime').value,amountMl:type==='pump'?+$('entryAmount').value||0:null,durationMin:+$('entryDuration').value||null,side:type==='nursing'?$('entrySide').value:null,quality:type==='pump'?$('entryQuality').value:null,note:$('entryNote').value.trim(),synced:false};S.entries.push(x);save();$('entryDialog').close();try{await pushMom(x);}catch{toast('Saved on device. Cloud will retry.');}render();});$('babyForm').addEventListener('submit',async e=>{e.preventDefault();const type=$('babyEventType').value;const x={id:`baby-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,babyId:S.baby.id,eventType:type,date:$('babyDate').value,time:$('babyTime').value,subtype:type==='diaper'?$('babySubtype').value:null,feedingType:type==='feeding'?$('babySubtype').value:null,amountOz:type==='feeding'?+$('babyAmount').value||0:null,note:$('babyNote').value.trim(),sourceFile:'MilkFlow',synced:false};S.babyEvents.push(x);save();$('babyDialog').close();try{await pushBabies([x]);}catch{toast('Saved on device. Cloud will retry.');}render();});$('authForm').addEventListener('submit',async e=>{e.preventDefault();try{await cloud.auth.signInWithEmailAndPassword($('authEmail').value.trim(),$('authPassword').value);$('authDialog').close();}catch(err){toast(err.message)}});$('signUpBtn').onclick=async()=>{try{await cloud.auth.createUserWithEmailAndPassword($('authEmail').value.trim(),$('authPassword').value);$('authDialog').close();}catch(err){toast(err.message)}};$('importFile').onchange=e=>{const f=e.target.files?.[0];if(f)importBackup(f);e.target.value='';};}
async function importBackup(file){let d;try{d=JSON.parse(await file.text())}catch{return toast('That file could not be read.');}let mom=[],baby=[],profile=null,schedule=null,overrides={};if(d.schema_version==='milkflow-family-bundle-2'){mom=Array.isArray(d.mom?.entries)?d.mom.entries:[];baby=Array.isArray(d.baby?.events)?d.baby.events.map(mapMigrationBaby):[];profile=d.mom?.profile||null;schedule=d.mom?.schedule||null;overrides=d.mom?.dailyOverrides||{};}else if(Array.isArray(d.events)){baby=d.events.filter(x=>x.owner_scope==='baby'&&String(x.date||'').startsWith('2026-')).map(mapMigrationBaby);}else if(Array.isArray(d.entries)){mom=d.entries;profile=d.profile||null;schedule=d.schedule||null;overrides=d.dailyOverrides||{};}if(!mom.length&&!baby.length)return toast('No compatible records found.');const mm=new Map(S.entries.map(e=>[e.id,e]));mom.forEach(e=>{if(e?.id&&!mm.has(e.id))mm.set(e.id,{...e,synced:false})});S.entries=[...mm.values()];const bm=new Map(S.babyEvents.map(e=>[e.id,e]));baby.forEach(e=>{if(e?.id&&!bm.has(e.id))bm.set(e.id,{...e,synced:false})});S.babyEvents=[...bm.values()];if(profile)S.profile={...S.profile,...profile};if(Array.isArray(schedule)&&schedule.length)S.schedule=schedule;S.dailyOverrides={...S.dailyOverrides,...overrides};save();if(S.cloud.enabled){toast('Imported. Saving to family cloud…');try{for(const e of S.entries.filter(e=>!e.synced))await pushMom(e);await pushBabies(S.babyEvents.filter(e=>!e.synced));await pushProfile();toast('Family history saved.');}catch{toast('Imported on this device. Cloud sync will retry.');}}else toast('Imported on this device. Sign in to sync.');setView(mom.length?'history':'baby-history');}
function mapMigrationBaby(x){return {id:x.migration_id||x.id||`baby-${Date.now()}-${Math.random()}`,babyId:x.baby_id||'saahas-2026',eventType:x.event_type||x.eventType,date:x.date,time:x.time||'',subtype:x.status||x.subtype||null,feedingType:x.feeding_type||x.feedingType||null,amountOz:x.amount_oz??x.amountOz??null,totalMinutes:x.total_minutes??x.totalMinutes??null,durationMinutes:x.duration_minutes??x.durationMinutes??null,note:x.note||'',sourceFile:x.source_file||x.sourceFile||'Baby Tracker',sourceRow:x.source_row||x.sourceRow||null,synced:false};}
async function initCloud(){const c=window.MILKFLOW_CONFIG||{};if(!c.enableCloudSync||!c.firebaseConfig||!window.firebase)return;try{if(!firebase.apps.length)firebase.initializeApp(c.firebaseConfig);cloud={auth:firebase.auth(),db:firebase.firestore()};try{await cloud.db.enablePersistence({synchronizeTabs:true})}catch{}cloud.auth.onAuthStateChanged(async u=>{S.cloud.userId=u?.uid||null;S.cloud.email=u?.email||null;S.cloud.enabled=!!u;save();if(u)await reconcile();render();});}catch(e){console.error(e);toast('Cloud connection needs attention.');}}
const user=()=>cloud?.db.collection('users').doc(S.cloud.userId);const momRef=()=>user().collection('entries');const babyRef=()=>user().collection('familyEvents');const profRef=()=>user().collection('private').doc('profile');
async function reconcile(){if(!cloud||!S.cloud.userId)return;try{const [ms,bs,ps]=await Promise.all([momRef().get(),babyRef().get(),profRef().get()]);const mm=new Map(ms.docs.map(d=>[d.id,{id:d.id,...d.data(),synced:true}]));S.entries.forEach(e=>{if(!mm.has(e.id))mm.set(e.id,e)});S.entries=[...mm.values()];const bm=new Map(bs.docs.map(d=>[d.id,{id:d.id,...d.data(),synced:true}]));S.babyEvents.forEach(e=>{if(!bm.has(e.id))bm.set(e.id,e)});S.babyEvents=[...bm.values()];if(ps.exists){const p=ps.data();S.profile={...S.profile,...(p.profile||{})};S.baby={...S.baby,...(p.baby||{})};if(Array.isArray(p.schedule))S.schedule=p.schedule;S.dailyOverrides={...S.dailyOverrides,...(p.dailyOverrides||{})};S.reminders={...S.reminders,...(p.reminders||{})};}for(const e of S.entries.filter(e=>!e.synced))await pushMom(e);await pushBabies(S.babyEvents.filter(e=>!e.synced));if(!ps.exists)await pushProfile();S.cloud.lastSync=new Date().toISOString();save();}catch(e){console.error(e);toast('Cloud sync needs attention.');}}
async function pushMom(e){if(!cloud||!S.cloud.userId)return;await momRef().doc(e.id).set({type:e.type,date:e.date,time:e.time||'',amountMl:e.amountMl??null,durationMin:e.durationMin??null,side:e.side||null,quality:e.quality||null,note:e.note||'',occurredAt:`${e.date}T${e.time||'00:00'}:00`,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});e.synced=true;save();}
async function pushBabies(arr){if(!cloud||!S.cloud.userId||!arr.length)return;for(let i=0;i<arr.length;i+=350){const batch=cloud.db.batch(),part=arr.slice(i,i+350);for(const e of part)batch.set(babyRef().doc(e.id),{...e,synced:true,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});await batch.commit();part.forEach(e=>e.synced=true);}save();}
async function pushProfile(){if(!cloud||!S.cloud.userId)return;await profRef().set({profile:S.profile,baby:S.baby,schedule:S.schedule,dailyOverrides:S.dailyOverrides,reminders:S.reminders,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});S.cloud.lastSync=new Date().toISOString();save();}
async function checkCloud(){if(!cloud||!S.cloud.userId)return toast('Sign in first.');try{const [m,b]=await Promise.all([momRef().get(),babyRef().get()]);toast(`Cloud: ${m.size} Mom · ${b.size} Baby`);}catch{toast('Could not verify cloud right now.');}}
async function toggleReminder(){if(S.reminders.enabled){S.reminders.enabled=false;save();await pushProfile();render();return;}if(!('Notification'in window))return toast('Notifications are not supported here.');const p=await Notification.requestPermission();if(p!=='granted')return toast('Allow notifications in browser settings.');S.reminders.enabled=true;save();await pushProfile();render();toast('Pump reminders enabled.');}
function tickReminders(){if(!S.reminders.enabled||!('Notification'in window)||Notification.permission!=='granted')return;const d=new Date(),m=d.getHours()*60+d.getMinutes(),dt=today();S.schedule.forEach((t,i)=>{const target=+t.slice(0,2)*60 + +t.slice(3)-(+S.reminders.leadMin||0),k=`${dt}-${i}-${target}`;if(Math.abs(m-target)<=1&&S.reminders.lastSentKey!==k&&dayP(dt).length<=i){try{new Notification('Pump reminder',{body:`Pump ${i+1} · ${to12(t)}`});}catch{}S.reminders.lastSentKey=k;save();}});}
initStatic();save();render();initCloud();tickReminders();setInterval(tickReminders,60000);
})();