(() => {
'use strict';

const STATE_KEY='milkflow-family-v4-state';
const CHAT_KEY='milkflow-family-chat-v1';
const PENDING_KEY='milkflow-family-chat-pending-v1';
const MAX_LOCAL=60;
const CLOUD_TIMEOUT_MS=18000;
const STATUS_TIMEOUT_MS=8000;
const STATUS_POLL_MS=1800;
const STATUS_POLL_LIMIT=22;
let busy=false;
let recoveryPromise=null;

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const pad=n=>String(n).padStart(2,'0');
const readState=()=>{try{return JSON.parse(localStorage.getItem(STATE_KEY)||'{}')||{};}catch{return {};}};
const readChat=()=>{try{const x=JSON.parse(localStorage.getItem(CHAT_KEY)||'[]');return Array.isArray(x)?x:[];}catch{return [];}};
const saveChat=a=>{try{localStorage.setItem(CHAT_KEY,JSON.stringify(a.slice(-MAX_LOCAL)));}catch{}};
const dateKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const dateShift=n=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return dateKey(d);};
const clock=d=>`${pad(d.getHours())}:${pad(d.getMinutes())}`;
const today=()=>dateKey(new Date());
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;

function endpointCandidates(){const cfg=window.MILKFLOW_CONFIG||{},list=[cfg.familyChatEndpoint,...(Array.isArray(cfg.familyChatEndpoints)?cfg.familyChatEndpoints:[])].map(x=>String(x||'').trim()).filter(Boolean);return [...new Set(list)];}
function endpoint(){return endpointCandidates()[0]||'';}
function readPending(){try{const x=JSON.parse(localStorage.getItem(PENDING_KEY)||'null');return x&&x.requestId&&x.message?x:null;}catch{return null;}}
function savePending(x){try{x?localStorage.setItem(PENDING_KEY,JSON.stringify(x)):localStorage.removeItem(PENDING_KEY);}catch{}}
function isOpen(){return document.getElementById('mfChatPanel')?.classList.contains('open');}
function to12(t){if(!t)return'—';const [h,m]=String(t).split(':').map(Number);if(!Number.isFinite(h)||!Number.isFinite(m))return String(t);return `${((h+11)%12)+1}:${pad(m)} ${h>=12?'PM':'AM'}`;}
function to12m(m){if(!Number.isFinite(m))return'—';const n=((Math.round(m)%1440)+1440)%1440,h=Math.floor(n/60),mm=n%60;return `${((h+11)%12)+1}:${pad(mm)} ${h>=12?'PM':'AM'}`;}
function shortDate(k){try{return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(new Date(`${k}T12:00:00`));}catch{return k;}}
function localTimestamp(){const d=new Date(),off=-d.getTimezoneOffset(),sign=off>=0?'+':'-',oh=pad(Math.floor(Math.abs(off)/60)),om=pad(Math.abs(off)%60);return `${dateKey(d)}T${clock(d)}:${pad(d.getSeconds())}${sign}${oh}:${om}`;}
function activeBabyId(s){return s.baby?.id||'saahas-2026';}
function livePumps(s){return(Array.isArray(s.entries)?s.entries:[]).filter(e=>e?.type==='pump'&&!e?.voidedAt&&e?.date&&e?.time);}
function liveBaby(s){const id=activeBabyId(s);return(Array.isArray(s.babyEvents)?s.babyEvents:[]).filter(e=>!e?.voidedAt&&!e?.exactSourceDuplicate&&(!e.babyId||e.babyId===id));}
function planActions(forTomorrow=false){return forTomorrow?[{id:'tomorrow6',label:'6 pumps tomorrow'},{id:'tomorrow5',label:'5 pumps tomorrow'}]:[{id:'replan',label:'Refresh today’s plan'},{id:'target6',label:'6 pumps today'},{id:'target5',label:'5 pumps today'}];}

function styles(){
  if(document.getElementById('mfChatStyles'))return;
  const s=document.createElement('style');s.id='mfChatStyles';s.textContent=`
  .mf-chat-btn{position:fixed;z-index:90;right:18px;bottom:24px;width:58px;height:58px;border:0;border-radius:50%;background:var(--mom,#7653c6);color:#fff;box-shadow:0 14px 34px rgba(36,30,63,.28);display:grid;place-items:center;cursor:pointer;transition:transform .18s ease,box-shadow .18s ease}.mf-chat-btn:hover{transform:translateY(-2px);box-shadow:0 17px 38px rgba(36,30,63,.32)}.mf-chat-btn svg{width:26px;height:26px}.mf-chat-btn .dot{position:absolute;right:3px;top:3px;width:12px;height:12px;border-radius:50%;background:#55c38f;border:2px solid var(--surface,#fff)}
  .mf-chat-panel{position:fixed;z-index:89;right:18px;bottom:94px;width:min(410px,calc(100vw - 24px));height:min(650px,74vh);background:var(--surface,#fff);color:var(--ink,#20202a);border:1px solid var(--line-soft,var(--line,#e7e5ed));border-radius:24px;box-shadow:0 24px 70px rgba(27,24,43,.22);overflow:hidden;display:none;grid-template-rows:auto 1fr auto}.mf-chat-panel.open{display:grid}
  .mf-chat-head{padding:14px 15px 12px;display:flex;align-items:center;gap:10px;border-bottom:1px solid var(--line-soft,var(--line,#eee));background:linear-gradient(145deg,color-mix(in srgb,var(--mom,#7653c6) 9%,var(--surface,#fff)),var(--surface,#fff))}.mf-chat-avatar{width:38px;height:38px;border-radius:14px;background:var(--mom,#7653c6);color:#fff;display:grid;place-items:center;font-weight:900}.mf-chat-head-text{min-width:0;flex:1}.mf-chat-head-text strong,.mf-chat-head-text small{display:block}.mf-chat-head-text strong{font-size:.95rem}.mf-chat-head-text small{font-size:.7rem;color:var(--muted,#74717d);margin-top:2px}.mf-chat-close{width:38px;height:38px;border:0;border-radius:12px;background:transparent;color:var(--muted,#777);font-size:1.4rem;cursor:pointer}
  .mf-chat-body{overflow:auto;padding:14px;display:flex;flex-direction:column;gap:10px;overscroll-behavior:contain}.mf-chat-welcome{padding:12px 13px;border-radius:16px;background:var(--surface-2,#f7f5fa);font-size:.78rem;line-height:1.5;color:var(--muted,#706d78)}.mf-chat-row{display:flex;flex-direction:column}.mf-chat-row.user{align-items:flex-end}.mf-chat-row.assistant{align-items:flex-start}.mf-chat-msg{max-width:88%;padding:10px 12px;border-radius:16px;font-size:.82rem;line-height:1.5;white-space:pre-wrap;overflow-wrap:anywhere}.mf-chat-row.user .mf-chat-msg{background:var(--mom,#7653c6);color:#fff;border-bottom-right-radius:5px}.mf-chat-row.assistant .mf-chat-msg{background:var(--surface-2,#f7f5fa);color:var(--ink,#222);border-bottom-left-radius:5px}.mf-chat-msg.pending{opacity:.86}.mf-chat-status{display:block;margin:4px 6px 0;color:var(--muted,#777);font-size:.66rem;font-weight:700}.mf-chat-retry{margin:6px 0 0 4px;border:1px solid var(--line-soft,var(--line,#e4e0eb));background:var(--surface,#fff);color:var(--ink,#222);border-radius:999px;padding:7px 10px;font:inherit;font-size:.68rem;font-weight:850;cursor:pointer}.mf-chat-actions{display:flex;gap:6px;flex-wrap:wrap;margin:6px 0 0 3px;max-width:92%}.mf-chat-actions button{border:1px solid var(--line-soft,var(--line,#e4e0eb));background:var(--surface,#fff);color:var(--ink,#222);border-radius:999px;padding:7px 10px;font:inherit;font-size:.68rem;font-weight:800;cursor:pointer}.mf-chat-actions button:first-child{background:color-mix(in srgb,var(--mom,#7653c6) 9%,var(--surface,#fff));border-color:color-mix(in srgb,var(--mom,#7653c6) 25%,var(--line,#e4e0eb))}.mf-chat-typing{font-size:.75rem;color:var(--muted,#777);padding:2px 5px}
  .mf-chat-quick{display:flex;gap:6px;overflow:auto;padding:0 14px 9px;scrollbar-width:none}.mf-chat-quick::-webkit-scrollbar{display:none}.mf-chat-quick button{white-space:nowrap;border:1px solid var(--line-soft,var(--line,#e6e3ec));background:var(--surface,#fff);color:var(--ink,#222);border-radius:999px;padding:7px 10px;font:inherit;font-size:.7rem;font-weight:750;cursor:pointer}
  .mf-chat-compose{border-top:1px solid var(--line-soft,var(--line,#eee));padding:10px;background:var(--surface,#fff)}.mf-chat-form{display:flex;align-items:flex-end;gap:8px}.mf-chat-input{flex:1;resize:none;min-height:44px;max-height:112px;border:1px solid var(--line-soft,var(--line,#dedbe6));border-radius:15px;background:var(--surface-2,#faf9fb);color:var(--ink,#222);padding:11px 12px;font:inherit;font-size:.83rem;line-height:1.35;outline:none}.mf-chat-input:focus{border-color:color-mix(in srgb,var(--mom,#7653c6) 55%,var(--line,#ddd))}.mf-chat-send{width:44px;height:44px;border:0;border-radius:14px;background:var(--mom,#7653c6);color:#fff;display:grid;place-items:center;cursor:pointer;font-size:1.1rem}.mf-chat-send:disabled{opacity:.45;cursor:default}.mf-chat-note{display:block;margin:7px 3px 0;font-size:.62rem;color:var(--muted,#777);line-height:1.35}
  @media(max-width:700px){.mf-chat-btn{right:14px;bottom:calc(78px + env(safe-area-inset-bottom));width:56px;height:56px}.mf-chat-panel{right:10px;bottom:calc(143px + env(safe-area-inset-bottom));width:calc(100vw - 20px);height:min(620px,70vh);border-radius:22px}}
  `;document.head.appendChild(s);
}

function context(){
  const s=readState();
  const cleanMom=e=>({type:e.type||null,date:e.date||null,time:e.time||null,amountMl:e.amountMl??null,durationMinutes:e.durationMinutes??e.durationMin??e.duration??null,side:e.side||null,voidedAt:e.voidedAt||null});
  const cleanBaby=e=>({babyId:e.babyId||e.baby_id||null,eventType:e.eventType||e.event_type||null,date:e.date||null,time:e.time||null,subtype:e.subtype||null,feedingType:e.feedingType||e.feeding_type||null,amountOz:e.amountOz??e.amount_oz??null,durationMinutes:e.durationMinutes??e.duration_minutes??null,totalMinutes:e.totalMinutes??e.total_minutes??null,leftMinutes:e.leftMinutes??e.left_minutes??null,rightMinutes:e.rightMinutes??e.right_minutes??null,side:e.side||null,weightLb:e.weightLb??e.weight_lb??null,weightOz:e.weightOz??e.weight_oz??null,lengthIn:e.lengthIn??e.length_in??null,headIn:e.headIn??e.head_in??null,milestoneId:e.milestoneId??e.milestone_id??null,milestoneText:e.milestoneText??e.milestone_text??null,milestoneGroup:e.milestoneGroup??e.milestone_group??null,milestoneMonth:e.milestoneMonth??e.milestone_month??null,voidedAt:e.voidedAt||null});
  let dynamicPlan=null;
  try{const p=window.MilkFlowDynamicPump?.getPlan?.();if(p)dynamicPlan={target:p.target,remaining:p.remaining,future:Array.isArray(p.future)?p.future:[],last:p.last?cleanMom(p.last):null,source:p.source||null};}catch{}
  let pumpChoices={todayTarget:dynamicPlan?.target||6,tomorrowTarget:null};try{const p=JSON.parse(localStorage.getItem('milkflow-pumping-coach-v1')||'{}');pumpChoices.tomorrowTarget=Number(p.dayTargets?.[dateShift(1)])||null;}catch{}
  return {currentLocalTime:localTimestamp(),timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone||null,currentWorkspace:s.ui?.workspace||null,pumpChoices,activeBaby:s.baby?{id:s.baby.id||null,name:s.baby.name||null,birthDate:s.baby.birthDate||null}:null,dynamicPlan,recentMom:(Array.isArray(s.entries)?s.entries:[]).filter(e=>!e?.voidedAt).sort((a,b)=>`${a.date||''}${a.time||''}`.localeCompare(`${b.date||''}${b.time||''}`)).slice(-40).map(cleanMom),recentBaby:(Array.isArray(s.babyEvents)?s.babyEvents:[]).filter(e=>!e?.voidedAt).sort((a,b)=>`${a.date||''}${a.time||''}`.localeCompare(`${b.date||''}${b.time||''}`)).slice(-80).map(cleanBaby),localConversation:readChat().slice(-16).map(m=>({role:m.role,text:String(m.text||'').slice(0,1200)}))};
}

function statusLabel(status){if(status==='sending')return'Sending…';if(status==='reconnecting')return'Reconnecting…';if(status==='polling')return'Finalizing response…';if(status==='waiting')return'Waiting for connection…';if(status==='failed')return'Automatic recovery stopped.';return'';}
function renderMessages(){
  const body=document.getElementById('mfChatBody');if(!body)return;const list=readChat();
  body.innerHTML=`<div class="mf-chat-welcome">Ask about your next pump, today’s total, the rolling 7-day pattern, or log a pump naturally. I’ll answer from your actual pumping record and live daily plan.</div>`+list.map((m,i)=>{const pending=m.role==='assistant'&&m.status&&m.status!=='completed',label=statusLabel(m.status);return `<div class="mf-chat-row ${m.role==='user'?'user':'assistant'}"><div class="mf-chat-msg${pending?' pending':''}">${esc(m.text||label||'Finishing response…')}</div>${pending&&label?`<small class="mf-chat-status">${esc(label)}</small>`:''}${m.role==='assistant'&&m.status==='failed'&&m.requestId?`<button type="button" class="mf-chat-retry" data-mf-retry="${esc(m.requestId)}">Retry</button>`:''}${m.role==='assistant'&&Array.isArray(m.actions)&&m.actions.length?`<div class="mf-chat-actions">${m.actions.map(a=>`<button type="button" data-mf-action="${esc(a.id)}" data-mf-message="${i}">${esc(a.label)}</button>`).join('')}</div>`:''}</div>`;}).join('');
  body.scrollTop=body.scrollHeight;
}
function add(role,text,extra={}){const list=readChat();list.push({role,text:String(text),at:Date.now(),...extra});saveChat(list);renderMessages();}
function upsertAssistant(requestId,text='',extra={}){const list=readChat();let i=list.findIndex(m=>m.role==='assistant'&&m.requestId===requestId);const next={role:'assistant',text:String(text||''),at:Date.now(),requestId,...extra};if(i>=0)list[i]={...list[i],...next};else list.push(next);saveChat(list);renderMessages();}
function updateAssistantStatus(requestId,status,text){const list=readChat(),i=list.findIndex(m=>m.role==='assistant'&&m.requestId===requestId);if(i<0)return;list[i]={...list[i],status,...(text!==undefined?{text:String(text)}:{}),at:Date.now()};saveChat(list);renderMessages();}
function findUserByRequest(requestId){return readChat().find(m=>m.role==='user'&&m.requestId===requestId)||null;}
function setBusy(v,label='MilkFlow is thinking…'){busy=v;const send=document.getElementById('mfChatSend'),input=document.getElementById('mfChatInput'),body=document.getElementById('mfChatBody');if(send)send.disabled=v;if(input)input.disabled=v;document.getElementById('mfChatTyping')?.remove();if(v&&body){const d=document.createElement('div');d.id='mfChatTyping';d.className='mf-chat-typing';d.textContent=label;body.appendChild(d);body.scrollTop=body.scrollHeight;}}

function parseDateFromText(text){const d=new Date();if(/\byesterday\b/i.test(text))d.setDate(d.getDate()-1);return dateKey(d);}
function parseExplicitTime(text){let m=String(text).match(/\b(1[0-2]|0?[1-9])(?::([0-5]\d))?\s*(a\.?m\.?|p\.?m\.?)\b/i);if(m){let h=+m[1],min=+(m[2]||0);const pm=/p/i.test(m[3]);if(h===12)h=0;if(pm)h+=12;return `${pad(h)}:${pad(min)}`;}m=String(text).match(/\b([01]?\d|2[0-3]):([0-5]\d)\b/);if(m)return `${pad(+m[1])}:${pad(+m[2])}`;if(/\b(now|just now|just pumped|just nursed|just fed|just changed)\b/i.test(text))return clock(new Date());return null;}
function parseMl(text){const m=String(text).match(/\b(\d{1,4}(?:\.\d+)?)\s*(?:ml|mL|millilit(?:er|re)s?)\b/i);return m?+m[1]:null;}
function parseOz(text){const m=String(text).match(/\b(\d{1,2}(?:\.\d+)?)\s*(?:oz|ounce|ounces)\b/i);return m?+m[1]:null;}
function parseMinutes(text){const m=String(text).match(/\b(\d{1,3})\s*(?:min|mins|minute|minutes)\b/i);return m?+m[1]:null;}
function parseNaturalAction(text){const q=String(text||'').trim(),date=parseDateFromText(q),time=parseExplicitTime(q),ml=parseMl(q),oz=parseOz(q),mins=parseMinutes(q),bottleWords=/\b(formula|breast\s*milk|expressed|bottle)\b/i.test(q),nursing=/\b(nurs(?:e|ed|ing)?|breast\s*feed|breastfed|breastfeeding)\b/i.test(q),diaper=/\b(diaper|nappy)\b/i.test(q);if(ml!=null&&time&&!bottleWords&&!nursing)return{kind:'pump',date,time,amountMl:ml};if(nursing&&mins!=null){const side=/\bright\b/i.test(q)?'right':/\bleft\b/i.test(q)?'left':/\bboth\b/i.test(q)?'both':null;return{kind:'nursing',date,time:time||clock(new Date()),durationMinutes:mins,side};}if((diaper||/\b(wet|poopy|poop|dirty|mixed)\s+diaper\b/i.test(q))&&/\b(wet|poopy|poop|dirty|mixed|both)\b/i.test(q)){const subtype=/\b(mixed|both)\b/i.test(q)?'both':/\b(poopy|poop|dirty)\b/i.test(q)?'poop':'wet';return{kind:'diaper',date,time:time||clock(new Date()),subtype};}if(oz!=null&&bottleWords){const feedingType=/\bformula\b/i.test(q)?'formula':/\b(breast\s*milk|expressed)\b/i.test(q)?'expressed_milk':null;if(feedingType)return{kind:'feeding',date,time:time||clock(new Date()),amountOz:oz,feedingType};}return null;}
function parsePlanCommand(text){const q=String(text||'').toLowerCase(),time=parseExplicitTime(text),tomorrow=/\btomorrow\b/.test(q);if(/\b(?:5|five)\s*(?:pump|pumps|sessions)\b/.test(q)&&(/today|tomorrow|switch|make|use|target|plan/.test(q)))return{kind:tomorrow?'tomorrowTarget':'target',target:5};if(/\b(?:6|six)\s*(?:pump|pumps|sessions)\b/.test(q)&&(/today|tomorrow|switch|make|use|target|plan/.test(q)))return{kind:tomorrow?'tomorrowTarget':'target',target:6};if(time&&/\b(next\s+pump|move\s+(?:my\s+)?next|set\s+(?:my\s+)?next|next\s+session)\b/.test(q))return{kind:'nextTime',time};if(/\b(recalculate|recalc|refresh|adjust|shift|update)\b.*\b(plan|schedule|times?)\b/.test(q)||/\bplan\s+(?:for\s+)?today\b/.test(q))return{kind:'replan'};return null;}

function broadcastState(oldRaw,newRaw){try{window.dispatchEvent(new StorageEvent('storage',{key:STATE_KEY,oldValue:oldRaw,newValue:newRaw,storageArea:localStorage,url:location.href}));}catch{window.dispatchEvent(new CustomEvent('milkflow:chat-data',{detail:{key:STATE_KEY}}));}}
function writeState(s){const oldRaw=localStorage.getItem(STATE_KEY);s.savedAt=Math.max(Date.now(),Number(s.savedAt||0)+1);const raw=JSON.stringify(s);localStorage.setItem(STATE_KEY,raw);broadcastState(oldRaw,raw);window.dispatchEvent(new CustomEvent('milkflow:chat-data',{detail:{key:STATE_KEY}}));}
async function syncMomEntry(e){const user=window.firebase?.auth?.().currentUser;if(!user||!window.firebase?.firestore)return false;try{const db=window.firebase.firestore();await db.collection('users').doc(user.uid).collection('entries').doc(e.id).set({type:e.type,date:e.date,time:e.time||'',amountMl:e.amountMl??null,durationMin:e.durationMin??null,side:e.side||null,quality:e.quality||null,note:e.note||'',source:e.source||'MilkFlow Chat',createdAt:e.createdAt||null,editedAt:e.editedAt||null,voidedAt:null,updatedAt:window.firebase.firestore.FieldValue.serverTimestamp()},{merge:true});return true;}catch(err){console.warn('Chat pump cloud sync deferred',err);return false;}}
async function syncBabyEntry(e){const user=window.firebase?.auth?.().currentUser;if(!user||!window.firebase?.firestore)return false;try{const db=window.firebase.firestore();await db.collection('users').doc(user.uid).collection('familyEvents').doc(e.id).set({...e,synced:true,updatedAt:window.firebase.firestore.FieldValue.serverTimestamp()},{merge:true});return true;}catch(err){console.warn('Chat baby cloud sync deferred',err);return false;}}

function pumpStats(s){const map={};for(const e of livePumps(s)){const d=map[e.date]||(map[e.date]={date:e.date,total:0,count:0,sessions:[]});d.total+=Number(e.amountMl)||0;d.count++;d.sessions.push(e);}for(const d of Object.values(map)){const o=Number(s.dailyOverrides?.[d.date]);if(Number.isFinite(o)&&o>d.total)d.total=o;}const rows=Object.values(map).sort((a,b)=>a.date.localeCompare(b.date)),highSession=livePumps(s).reduce((best,e)=>(Number(e.amountMl)||0)>(Number(best?.amountMl)||0)?e:best,null),done=rows.filter(r=>r.date<today()),highDay=done.reduce((best,r)=>r.total>(best?.total||-1)?r:best,null);return{rows,highSession,highDay};}
function planText(prefix='Here’s today’s live plan 💛'){
  try{const p=window.MilkFlowDynamicPump?.getPlan?.();if(!p)return`${prefix}\nThe planner is still loading.`;const done=p.actual?.length||0;if(!p.remaining)return`${prefix}\nYou’ve completed ${done} of ${p.target} pumps — target reached for today 🎉`;const times=(p.future||[]).map((m,i)=>`${i===0?'Next':'Then'} ${to12m(m)}`).join(' · ');return`${prefix}\n${done} of ${p.target} done${times?`\n${times}`:''}\nI’ll keep shifting the remaining times from what you actually log today.`;}catch{return`${prefix}\nThe planner is still loading.`;}
}
function nextPumpLine(){try{const p=window.MilkFlowDynamicPump?.getPlan?.();if(p?.remaining&&p.future?.length)return `💕 Next pump: around ${to12m(p.future[0]-10)}–${to12m(p.future[0]+10)}.`;if(p&&!p.remaining)return `💕 You’ve reached today’s ${p.target||6}-pump target.`;}catch{}return'';}
function friendlyPumpReply(entry,duplicate=false){const s=readState(),stats=pumpStats(s),rows=stats.rows.slice(-7),day=stats.rows.find(r=>r.date===entry.date),recent=readChat().slice(-8).filter(m=>m.role==='user').map(m=>m.text).join(' '),lateStart=/slept|sleep|woke|alarm|overslept|slept in|tired/i.test(recent),lines=[];lines.push(duplicate?`I already have that one 💛 ${shortDate(entry.date)} · ${to12(entry.time)} · ${entry.amountMl} mL, so I didn’t duplicate it.`:`Got it! 🍼💛 ${shortDate(entry.date)} · ${to12(entry.time)} · ${entry.amountMl} mL logged.`);if(!duplicate&&lateStart&&entry.date===today())lines.push(`And after the rough sleep/start, that’s a strong way to begin the day. We’ll move the schedule with you instead of making you chase the old clock.`);if(day)lines.push(`\n🌷 ${entry.date===today()?'Today so far':shortDate(entry.date)}: ${day.total} mL · ${day.count} pump${day.count===1?'':'s'}`);if(rows.length)lines.push(`\nRolling 7 days\n${rows.map(r=>`${r.date===today()?'• Today':`• ${shortDate(r.date)}`} — ${r.total} mL · ${r.count} pump${r.count===1?'':'s'}`).join('\n')}`);if(stats.highSession)lines.push(`\n🏆 Highest session: ${stats.highSession.amountMl} mL — ${shortDate(stats.highSession.date)}`);if(stats.highDay)lines.push(`🏆 Best completed day: ${stats.highDay.total} mL — ${shortDate(stats.highDay.date)}`);const next=entry.date===today()?nextPumpLine():'';if(next)lines.push(next);return lines.join('\n');}
function babyTodayReply(kind,e,duplicate=false){const s=readState(),name=s.baby?.name||'Baby',ev=liveBaby(s).filter(x=>x.date===e.date),n=ev.filter(x=>x.eventType==='nursing'),di=ev.filter(x=>x.eventType==='diaper'),feeds=ev.filter(x=>x.eventType==='feeding'),wet=di.filter(x=>String(x.subtype).toLowerCase()==='wet').length,poop=di.filter(x=>['poop','dirty'].includes(String(x.subtype).toLowerCase())).length,both=di.filter(x=>['both','mixed'].includes(String(x.subtype).toLowerCase())).length;let first='';if(kind==='nursing')first=`${duplicate?'Already logged':'Logged'} 💕 ${e.durationMinutes} min nursing${e.side?` on the ${e.side}`:''} at ${to12(e.time)}.`;if(kind==='diaper')first=`${duplicate?'Already logged':'Logged'} 💛 ${e.subtype==='wet'?'Wet':e.subtype==='poop'?'Poopy':'Mixed'} diaper at ${to12(e.time)}.`;if(kind==='feeding')first=`${duplicate?'Already logged':'Logged'} 🍼 ${e.amountOz} oz ${e.feedingType==='formula'?'formula':'breast milk'} at ${to12(e.time)}.`;return `${first}\n\n${name} today: ${n.length} nursing · ${feeds.length} bottle feed${feeds.length===1?'':'s'} · ${wet} wet · ${poop} poopy · ${both} mixed.`;}

async function performAction(a){const s=readState();if(a.kind==='pump'){const existing=livePumps(s).find(e=>e.date===a.date&&e.time===a.time&&Number(e.amountMl)===Number(a.amountMl));if(existing)return{reply:friendlyPumpReply(existing,true),duplicate:true};const e={id:uid('chat-pump'),type:'pump',date:a.date,time:a.time,amountMl:a.amountMl,durationMin:null,side:null,quality:null,note:'',source:'MilkFlow Chat',createdAt:new Date().toISOString(),synced:false};s.entries=Array.isArray(s.entries)?s.entries:[];s.entries.push(e);s.last={...(s.last||{}),pumpMl:a.amountMl};writeState(s);await syncMomEntry(e);return{reply:friendlyPumpReply(e,false)};}const events=Array.isArray(s.babyEvents)?s.babyEvents:[],bid=activeBabyId(s);let e;if(a.kind==='nursing')e={id:uid('chat-baby'),babyId:bid,eventType:'nursing',date:a.date,time:a.time,durationMinutes:a.durationMinutes,totalMinutes:a.durationMinutes,side:a.side||null,sourceFile:'MilkFlow Chat',createdAt:new Date().toISOString(),synced:false};if(a.kind==='diaper')e={id:uid('chat-baby'),babyId:bid,eventType:'diaper',date:a.date,time:a.time,subtype:a.subtype,sourceFile:'MilkFlow Chat',createdAt:new Date().toISOString(),synced:false};if(a.kind==='feeding')e={id:uid('chat-baby'),babyId:bid,eventType:'feeding',date:a.date,time:a.time,feedingType:a.feedingType,amountOz:a.amountOz,sourceFile:'MilkFlow Chat',createdAt:new Date().toISOString(),synced:false};if(!e)return null;const existing=events.find(x=>!x?.voidedAt&&x.babyId===bid&&x.eventType===e.eventType&&x.date===e.date&&x.time===e.time&&String(x.subtype||'')===String(e.subtype||'')&&String(x.feedingType||'')===String(e.feedingType||'')&&Number(x.amountOz||0)===Number(e.amountOz||0)&&Number(x.durationMinutes??x.totalMinutes??0)===Number(e.durationMinutes??e.totalMinutes??0)&&String(x.side||'')===String(e.side||''));if(existing)return{reply:babyTodayReply(a.kind,existing,true),duplicate:true};events.push(e);s.babyEvents=events;if(a.kind==='nursing')s.last={...(s.last||{}),nursingMin:a.durationMinutes};writeState(s);await syncBabyEntry(e);return{reply:babyTodayReply(a.kind,e,false)};}
function performPlanCommand(cmd){const api=window.MilkFlowDynamicPump;if(!api)return{reply:'The live planner is still loading. Open Mom Home once and try again.'};if(cmd.kind==='target'){api.setTodayTarget?.(cmd.target);return{reply:planText(`Done 💛 I changed today to ${cmd.target} pumps. This applies only to today.`),actions:planActions()};}if(cmd.kind==='tomorrowTarget'){api.setTomorrowTarget?.(cmd.target);return{reply:`Done 💛 Tomorrow is set to ${cmd.target} pumps. Today stays unchanged, and the choice will not repeat on later days.`,actions:planActions(true)};}if(cmd.kind==='nextTime'){const m=Number(cmd.time.slice(0,2))*60+Number(cmd.time.slice(3));api.setTodayNextTime?.(m);return{reply:planText(`Done 💛 I moved the next pump toward ${to12(cmd.time)} and rebuilt the rest of today around it.`),actions:planActions()};}return{reply:planText('I recalculated today from what you’ve actually logged so far 💛'),actions:planActions()};}
async function handleChatAction(id){if(busy)return;let cmd;if(id==='target5')cmd={kind:'target',target:5};else if(id==='target6')cmd={kind:'target',target:6};else if(id==='tomorrow5')cmd={kind:'tomorrowTarget',target:5};else if(id==='tomorrow6')cmd={kind:'tomorrowTarget',target:6};else cmd={kind:'replan'};const out=performPlanCommand(cmd);add('assistant',out.reply,{actions:out.actions});}

function localAnswer(q){const s=readState(),text=String(q||'').toLowerCase(),baby=liveBaby(s);if(/tomorrow/.test(text)&&/\b(5|6|five|six|pump|plan|schedule)\b/.test(text)){let chosen=null;try{const p=JSON.parse(localStorage.getItem('milkflow-pumping-coach-v1')||'{}');chosen=Number(p.dayTargets?.[dateShift(1)])||null;}catch{}return chosen?`Tomorrow is currently set to ${chosen} pumps 💛 This is a one-day choice and will not carry into the following day.`:`Tomorrow is not chosen yet. Since you’re still in the early postpartum supply-building period, 6 is the steadier default; 5 can be a one-day option when the day is too compressed. Your choice will apply only to tomorrow.`;}if(/next.*pump|pump.*next|when.*pump/.test(text))return planText('Here’s what I’d use for the next pump 💛');if(/7.?day|rolling|pump.*table|pumping.*summary/.test(text)){const st=pumpStats(s),rows=st.rows.slice(-7);if(!rows.length)return'I don’t see pump records on this device yet.';return`🌷 Rolling 7 days\n${rows.map(r=>`• ${shortDate(r.date)} — ${r.total} mL · ${r.count} pump${r.count===1?'':'s'}`).join('\n')}${st.highSession?`\n\n🏆 Highest session: ${st.highSession.amountMl} mL — ${shortDate(st.highSession.date)}`:''}${st.highDay?`\n🏆 Best completed day: ${st.highDay.total} mL — ${shortDate(st.highDay.date)}`:''}`;}if(/sleep|slept|alarm|woke|wake|tired|exhausted|overslept/.test(text)){const p=window.MilkFlowDynamicPump?.getPlan?.(),next=p?.future?.length?` Your current next-pump window is about ${to12m(p.future[0]-10)}–${to12m(p.future[0]+10)}.`:'';return`That sounds like a rough stretch of sleep 💛 You don’t have to chase the old clock today. We can let the remaining plan move from the pumps you actually log.${next}`;}if(/baby|breast|nurs|diaper|wet|poop|poopy|mixed|feed/.test(text)){const d=today(),ev=baby.filter(e=>e.date===d),n=ev.filter(e=>e.eventType==='nursing'),di=ev.filter(e=>e.eventType==='diaper'),f=ev.filter(e=>e.eventType==='feeding'),mins=n.reduce((x,e)=>x+(Number(e.durationMinutes??e.totalMinutes)||0),0),wet=di.filter(e=>String(e.subtype).toLowerCase()==='wet').length,poop=di.filter(e=>['poop','dirty'].includes(String(e.subtype).toLowerCase())).length,both=di.filter(e=>['both','mixed'].includes(String(e.subtype).toLowerCase())).length;return`Today for ${s.baby?.name||'Baby'} 💛\n${n.length} nursing${mins?` · ${mins} min`:''}\n${f.length} bottle feed${f.length===1?'':'s'}\n${wet} wet · ${poop} poopy · ${both} mixed`;}return null;}
function shouldOfferPlanActions(message,reply=''){return/\b(pump|pumping|schedule|plan|sleep|slept|alarm|tired|late|woke|wake)\b/i.test(`${message} ${reply}`);}
function replyActions(message,reply=''){return shouldOfferPlanActions(message,reply)?planActions(/\btomorrow\b/i.test(message)):undefined;}

const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function postCloud(url,token,payload,timeoutMs){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify(payload),signal:controller.signal});const data=await r.json().catch(()=>({}));return{http:r.status,ok:r.ok,data};}finally{clearTimeout(timer);}}
function completeCloudRequest(pending,data){const reply=String(data?.reply||'I could not form a response.');upsertAssistant(pending.requestId,reply,{status:'completed',actions:replyActions(pending.message,reply),cloudRequest:true,responseId:data?.responseId||null});if(readPending()?.requestId===pending.requestId)savePending(null);}
async function recoverLegacyHistory(pending,user){const db=window.firebase?.firestore?.();if(!db||!user?.uid)return null;try{const snap=await db.collection('users').doc(user.uid).collection('familyChatMessages').orderBy('createdAt','desc').limit(36).get(),rows=snap.docs.map(d=>{const x=d.data()||{},ts=typeof x.createdAt?.toMillis==='function'?x.createdAt.toMillis():0;return{role:x.role,text:String(x.text||''),ts,responseId:x.responseId||null};}).filter(x=>x.ts);const floor=Number(pending.createdAt||0)-5000,users=rows.filter(x=>x.role==='user'&&x.text===pending.message&&x.ts>=floor).sort((a,b)=>b.ts-a.ts);if(!users.length)return null;const u=users[0],assistant=rows.filter(x=>x.role==='assistant'&&x.ts>=u.ts-1500&&x.ts<=u.ts+45000).sort((a,b)=>Math.abs(a.ts-u.ts)-Math.abs(b.ts-u.ts))[0];return assistant?{ok:true,status:'completed',reply:assistant.text,responseId:assistant.responseId,source:'history-recovery'}:null;}catch(err){console.warn('Legacy chat history recovery unavailable',err);return null;}}
async function recoverCloudRequest(pending,user){
  if(recoveryPromise)return recoveryPromise;
  recoveryPromise=(async()=>{const urls=endpointCandidates();if(!urls.length)throw new Error('No family chat endpoint');const token=await user.getIdToken();let started=false,serverSupportsRecovery=false,retriedRun=false,lastError=null;
    updateAssistantStatus(pending.requestId,'sending');savePending({...pending,status:'sending',lastAttemptAt:Date.now()});
    try{const r=await postCloud(urls[0],token,{mode:'run',requestId:pending.requestId,message:pending.message,context:context()},CLOUD_TIMEOUT_MS);if(r.ok&&r.data?.ok){completeCloudRequest(pending,r.data);return r.data;}if(r.http===202&&r.data?.status==='processing'){started=true;serverSupportsRecovery=true;}else lastError=new Error(r.data?.error||`Request failed (${r.http})`);}catch(err){lastError=err;}
    updateAssistantStatus(pending.requestId,'polling');savePending({...pending,status:'polling',lastAttemptAt:Date.now()});
    for(let attempt=0;attempt<STATUS_POLL_LIMIT;attempt++){
      let missingOnRecoveryServer=false;
      for(const url of urls){try{const r=await postCloud(url,token,{mode:'status',requestId:pending.requestId},STATUS_TIMEOUT_MS);if(r.ok&&r.data?.ok&&r.data?.status==='completed'){completeCloudRequest(pending,r.data);return r.data;}if(r.http===202&&r.data?.status==='processing'){started=true;serverSupportsRecovery=true;continue;}if(r.http===404&&r.data?.status==='missing'){serverSupportsRecovery=true;missingOnRecoveryServer=true;continue;}if(r.data?.status==='failed'){serverSupportsRecovery=true;lastError=new Error(r.data?.error||'Request failed');continue;}}catch(err){lastError=err;}}
      if(serverSupportsRecovery&&missingOnRecoveryServer&&!started&&!retriedRun){retriedRun=true;updateAssistantStatus(pending.requestId,'reconnecting');savePending({...pending,status:'reconnecting',lastAttemptAt:Date.now()});const url=urls[1]||urls[0];try{const r=await postCloud(url,token,{mode:'run',requestId:pending.requestId,message:pending.message,context:context()},CLOUD_TIMEOUT_MS);if(r.ok&&r.data?.ok){completeCloudRequest(pending,r.data);return r.data;}if(r.http===202&&r.data?.status==='processing'){started=true;}else lastError=new Error(r.data?.error||`Request failed (${r.http})`);}catch(err){lastError=err;}updateAssistantStatus(pending.requestId,'polling');}
      const legacy=await recoverLegacyHistory(pending,user);if(legacy){completeCloudRequest(pending,legacy);return legacy;}
      if(!serverSupportsRecovery&&attempt>=2)break;
      await sleep(STATUS_POLL_MS);
    }
    throw lastError||new Error('Timed out waiting for final response');
  })();
  try{return await recoveryPromise;}finally{recoveryPromise=null;}
}
async function resumePending(){
  const pending=readPending();if(!pending||busy)return;const user=window.firebase?.auth?.().currentUser;if(!user){updateAssistantStatus(pending.requestId,'waiting');return;}
  setBusy(true,'Finishing your reply…');try{await recoverCloudRequest(pending,user);}catch(err){console.warn('Chat recovery exhausted',err);const fallback=localAnswer(pending.message);if(fallback){upsertAssistant(pending.requestId,fallback,{status:'completed',localFallback:true,actions:replyActions(pending.message,fallback)});savePending(null);}else{updateAssistantStatus(pending.requestId,'failed','I couldn’t finish that reply automatically. Your tracker data is safe.');}}finally{setBusy(false);document.getElementById('mfChatInput')?.focus();}
}
async function retryRequest(requestId){if(busy)return;const userMsg=findUserByRequest(requestId);if(!userMsg)return;const pending={requestId,message:String(userMsg.text||''),createdAt:userMsg.at||Date.now(),status:'reconnecting',lastAttemptAt:Date.now()};savePending(pending);upsertAssistant(requestId,'',{status:'reconnecting'});await resumePending();}
async function sendMessage(text){
  if(busy)return;const message=String(text||'').trim();if(!message)return;const input=document.getElementById('mfChatInput');if(input){input.value='';input.style.height='44px';}
  const planCmd=parsePlanCommand(message);if(planCmd){add('user',message);const out=performPlanCommand(planCmd);add('assistant',out.reply,{actions:out.actions});return;}
  const action=parseNaturalAction(message);if(action){add('user',message);setBusy(true);try{const out=await performAction(action);add('assistant',out?.reply||'Logged 💛',{localAction:true,actions:action.kind==='pump'?planActions():undefined});}catch(err){console.error(err);add('assistant','I couldn’t save that entry. Your existing tracker data is safe — please try once more.');}finally{setBusy(false);document.getElementById('mfChatInput')?.focus();}return;}
  const local=localAnswer(message),url=endpoint(),user=window.firebase?.auth?.().currentUser;if(!url||!user){add('user',message);if(local){add('assistant',local,{localFallback:true,actions:replyActions(message,local)});return;}add('assistant',!url?'The pumping assistant connection is not configured yet.':'I can still answer pump-plan questions from this device, but sign in to your Family account for open-ended coaching.');if(!user){try{document.getElementById('authDialog')?.showModal();}catch{}}return;}
  const requestId=uid('chatreq');const pending={requestId,message,createdAt:Date.now(),status:'sending',lastAttemptAt:Date.now()};add('user',message,{requestId});upsertAssistant(requestId,'',{status:'sending'});savePending(pending);await resumePending();
}

function toggle(force){const p=document.getElementById('mfChatPanel');if(!p)return;const open=typeof force==='boolean'?force:!p.classList.contains('open');p.classList.toggle('open',open);document.getElementById('mfChatButton')?.setAttribute('aria-expanded',String(open));if(open){renderMessages();setTimeout(()=>document.getElementById('mfChatInput')?.focus(),80);}}
function mount(){
  if(document.getElementById('mfChatButton'))return;styles();const panel=document.createElement('section');panel.id='mfChatPanel';panel.className='mf-chat-panel';panel.setAttribute('aria-label','MilkFlow pumping chat');panel.innerHTML=`<div class="mf-chat-head"><div class="mf-chat-avatar">M</div><div class="mf-chat-head-text"><strong>Pumping chat</strong><small>Your pump log, totals, and daily plan</small></div><button id="mfChatClose" class="mf-chat-close" type="button" aria-label="Close chat">×</button></div><div id="mfChatBody" class="mf-chat-body"></div><div><div class="mf-chat-quick"><button type="button" data-mf-prompt="When should I pump next?">Next pump</button><button type="button" data-mf-prompt="Show my rolling 7-day pumping summary.">7-day pumping</button><button type="button" data-mf-prompt="Recalculate my plan for today based on how the day is going.">Adjust today</button><button type="button" data-mf-prompt="Help me choose 5 or 6 pumps tomorrow.">Tomorrow’s plan</button></div><div class="mf-chat-compose"><form id="mfChatForm" class="mf-chat-form"><textarea id="mfChatInput" class="mf-chat-input" rows="1" placeholder="Ask about pumping or log a session…" aria-label="Message MilkFlow"></textarea><button id="mfChatSend" class="mf-chat-send" type="submit" aria-label="Send">➤</button></form><small class="mf-chat-note">Pumping answers use your actual log and live plan. A 5- or 6-pump choice applies only to the day you name.</small></div></div>`;
  const btn=document.createElement('button');btn.id='mfChatButton';btn.className='mf-chat-btn';btn.type='button';btn.setAttribute('aria-label','Open MilkFlow chat');btn.setAttribute('aria-expanded','false');btn.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4Z"/><path d="M8 9h8M8 13h5"/></svg><span class="dot"></span>';document.body.append(panel,btn);
  btn.addEventListener('click',()=>toggle());document.getElementById('mfChatClose').addEventListener('click',()=>toggle(false));document.getElementById('mfChatForm').addEventListener('submit',e=>{e.preventDefault();sendMessage(document.getElementById('mfChatInput').value);});document.getElementById('mfChatInput').addEventListener('input',e=>{e.target.style.height='44px';e.target.style.height=`${Math.min(112,e.target.scrollHeight)}px`;});document.getElementById('mfChatInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();document.getElementById('mfChatForm').requestSubmit();}});panel.addEventListener('click',e=>{const retry=e.target.closest('[data-mf-retry]');if(retry){retryRequest(retry.dataset.mfRetry);return;}const a=e.target.closest('[data-mf-action]');if(a){handleChatAction(a.dataset.mfAction);return;}const b=e.target.closest('[data-mf-prompt]');if(b)sendMessage(b.dataset.mfPrompt);});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&isOpen())toggle(false);});window.addEventListener('online',resumePending);window.addEventListener('pageshow',()=>setTimeout(resumePending,250));renderMessages();setTimeout(resumePending,700);
}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',mount);else mount();
})();
